name: Pycodestyle Check

on:
  push:
    branches:
      - main

jobs:
  pycodestyle:
    name: Check Syntax with Pycodestyle
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pycodestyle

      - name: Run Pycodestyle
        run: |
          pycodestyle .

